apiVersion: v1
kind: Service
metadata:
  name: judge-opinioner-service
spec:
  selector:
    app: judge-opinioner
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
  type: LoadBalancer